export const PLAYER_COLOR_VALUES = {
  white:  '#e0e0e0',
  black:  '#303030',
  purple: '#9030d0',
  green:  '#30b050',
};

export const GAMES = {
  hr: {
    name: 'Hero Realms',
    emoji: '⚔️',
    desc: 'Life tracker — survive longer than your opponents',
    direction: 'down',
    minPlayers: 2,
    maxPlayers: 4,
    defaultPlayers: 2,
    defaultStart: 50,
    startField: 'Starting HP',
    tile: {
      bg: '#051808',
      border: '#145414',
      stripe: 'linear-gradient(90deg, #1c8c2a, #40d458)',
      nameColor: '#88ff99',
      playBg: '#145a1e',
      hoverShadow: 'rgba(18,140,40,0.28)',
      font: "'Cinzel', serif",
    },
    theme: {
      '--bg':        '#041304',
      '--card-bg':   '#061c06',
      '--border':    '#1a641a',
      '--accent':    '#30dc50',
      '--text':      '#c0ffc8',
      '--game-font': "'Cinzel', serif",
    }
  },
  azul: {
    name: 'Azul',
    emoji: '🔷',
    desc: 'VP counter — score rises as you tile your palace',
    direction: 'up',
    minPlayers: 2,
    maxPlayers: 4,
    defaultPlayers: 2,
    defaultStart: 0,
    startField: null,
    tile: {
      bg: '#020e1a',
      border: '#0d4a7a',
      stripe: 'linear-gradient(90deg, #0d6eaa, #29b6f6)',
      nameColor: '#7dd6ff',
      playBg: '#0a4870',
      hoverShadow: 'rgba(10,100,180,0.30)',
      font: "'Cinzel', serif",
    },
    theme: {
      '--bg':        '#010c18',
      '--card-bg':   '#041525',
      '--border':    '#0d5888',
      '--accent':    '#29b6f6',
      '--text':      '#b0e8ff',
      '--game-font': "'Cinzel', serif",
    }
  },
  rftg: {
    name: 'Race for the Galaxy',
    emoji: '🚀',
    desc: 'VP counter — score rises as you build your empire',
    direction: 'up',
    minPlayers: 2,
    maxPlayers: 4,
    defaultPlayers: 2,
    defaultStart: 0,
    startField: null,
    vpTokens: true,
    tile: {
      bg: '#0c0920',
      border: '#30246a',
      stripe: 'linear-gradient(90deg, #5030b0, #8858e0)',
      nameColor: '#bca8ff',
      playBg: '#4a30a8',
      hoverShadow: 'rgba(70,40,180,0.28)',
      font: "'Orbitron', sans-serif",
    },
    theme: {
      '--bg':        '#090817',
      '--card-bg':   '#0d0c22',
      '--border':    '#342872',
      '--accent':    '#8858e0',
      '--text':      '#ccc0ff',
      '--game-font': "'Orbitron', sans-serif",
    }
  },
  yomi: {
    name: 'Yomi',
    emoji: '👊',
    desc: 'HP tracker — 1v1 fighting game card duel',
    direction: 'down',
    minPlayers: 2,
    maxPlayers: 2,
    defaultPlayers: 2,
    defaultStart: 100,
    startField: 'Starting HP',
    tile: {
      bg: '#0b0b0b',
      border: '#380000',
      stripe: 'linear-gradient(90deg, #8c0000, #cc1818)',
      nameColor: '#ff6868',
      playBg: '#720000',
      hoverShadow: 'rgba(110,0,0,0.35)',
      font: "'Russo One', sans-serif",
    },
    theme: {
      '--bg':        '#070707',
      '--card-bg':   '#101010',
      '--border':    '#3e0000',
      '--accent':    '#e83030',
      '--text':      '#ff8080',
      '--game-font': "'Russo One', sans-serif",
    }
  },
  emel: {
    name: 'Eight Minute Empire Legends',
    emoji: '🏰',
    desc: 'VP counter — conquer territories across the empire',
    direction: 'up',
    minPlayers: 2,
    maxPlayers: 4,
    defaultPlayers: 2,
    defaultStart: 0,
    startField: null,
    playerColors: ['white', 'black', 'purple', 'green'],
    tile: {
      bg: '#120d05',
      border: '#6a4208',
      stripe: 'linear-gradient(90deg, #8a5a08, #d4a020)',
      nameColor: '#e8c060',
      playBg: '#6a4a10',
      hoverShadow: 'rgba(160,100,0,0.32)',
      font: "'Cinzel', serif",
    },
    theme: {
      '--bg':        '#100c06',
      '--card-bg':   '#1a1208',
      '--border':    '#5a3a0a',
      '--accent':    '#d4a020',
      '--text':      '#e8d0a0',
      '--game-font': "'Cinzel', serif",
    }
  }
};
